version: '3'

services:
    mysql:
        container_name: events_mysql
        image: mysql:5.7
        ports:
            - 3309:3306
        volumes:
            - /data/mysql:/var/lib/mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: docker
            MYSQL_PASSWORD: docker
            MYSQL_DATABASE: docker
        networks:
            default:
                ipv4_address: 172.31.0.11
    nginx:
        container_name: events_nginx
        image: nginx:1.13-alpine
        ports:
            - 80:80
        restart: always
        volumes:
            - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
            - ../:/var/www/html
        depends_on:
            - php
    php:
        container_name: events_php
        build:
            context: ./php
            args:
                - PROJECT_PATH=${PROJECT_PATH:-/var/www/events}
                - INSTALL_XDEBUG=${DEV_MODE:-true}
                - PUID=${PUID:-1001}
        expose:
            - 9000
        restart: always
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
            - "${SERVER_NAME_BASE}:${DOCKER_HOST_IP}"
        volumes:
            - ./php/conf/php.ini:/usr/local/etc/php/conf.d/custom.ini
            - ../:/var/www/html

networks:
    default:
        driver: bridge
        ipam:
            config:
                - subnet: 172.31.0.0/20